### ISSUE TITLE
Add support for swagger or something similar

### ISSUE THREAD

**Issue by wonderwomancode** [unlock-protocol/docs#69] opened 2022-07-20 22:30 UTC
![Screen Shot 2022-07-20 at 3 30 03 PM](https://user-images.githubusercontent.com/18197239/180093464-e4d5e174-82bd-4664-8428-151ab80e6fb9.png)
![Screen Shot 2022-07-20 at 3 31 25 PM](https://user-images.githubusercontent.com/18197239/180093607-f7397372-7c25-4794-a2bc-d3c6b5d3fe0c.png)

**Comment by searchableguy** [comment] 2022-07-20 22:57
Already have it. Just not enabled or in front.

**Comment by searchableguy** [comment] 2022-07-20 22:58
Duplicate of https://github.com/unlock-protocol/docs/issues/43

**Closed** 2022-07-20 22:57 UTC

**Comment by searchableguy** [comment] 2022-07-20 22:59
Although we should fix this up. Didn't we decide on removing this for the time being?
